version: '3'

services:
  db0:
    container_name: db0
    hostname: db0
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Europe/Zurich"
    volumes: 
      - ./data:/data
    networks:
      sym_net:
        ipv4_address: 172.16.10.100
  
  db1:
    container_name: db1
    hostname: db1
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Europe/Zurich"
    volumes: 
      - ./data:/data
    networks:
      sym_net:
        ipv4_address: 172.16.10.101

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   ports:
  #     - 8888:8080
  #   networks:
  #     sym_net:
  #       ipv4_address: 172.16.10.200
  
  sym0:
    container_name: sym0
    hostname: sym0
    build: .
    depends_on:
      - db0
    environment:
      url_jarsetup: http://data.predestined.de/index.php/s/95Zt4fQ9absagEi/download
      TZ: "Europe/Zurich"
    networks:
      sym_net:
        ipv4_address: 172.16.10.10

  sym1:
    container_name: sym1
    hostname: sym1
    build: .
    depends_on:
      - db1
    environment:
      url_jarsetup: http://data.predestined.de/index.php/s/95Zt4fQ9absagEi/download
      TZ: "Europe/Zurich"
    networks:
      sym_net:
        ipv4_address: 172.16.10.11

networks:
  sym_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.10.0/24